/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IWebbNFT__factory } from "./IWebbNFT__factory";
export { WebbMultimint__factory } from "./WebbMultimint__factory";
