"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WebbMultimint__factory = exports.IWebbNFT__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IWebbNFT__factory_1 = require("./IWebbNFT__factory");
Object.defineProperty(exports, "IWebbNFT__factory", { enumerable: true, get: function () { return IWebbNFT__factory_1.IWebbNFT__factory; } });
var WebbMultimint__factory_1 = require("./WebbMultimint__factory");
Object.defineProperty(exports, "WebbMultimint__factory", { enumerable: true, get: function () { return WebbMultimint__factory_1.WebbMultimint__factory; } });
