/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IWebbNFT,
  IWebbNFTInterface,
} from "../../WebbMultimint.sol/IWebbNFT";

const _abi = [
  {
    inputs: [],
    name: "maxID",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IWebbNFT__factory {
  static readonly abi = _abi;
  static createInterface(): IWebbNFTInterface {
    return new utils.Interface(_abi) as IWebbNFTInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IWebbNFT {
    return new Contract(address, _abi, signerOrProvider) as IWebbNFT;
  }
}
