"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WebbMultimint__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [],
        name: "multimint",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
const _bytecode = "0x6080604052600080546001600160a01b03191673f639b4ebb77df1ed4b5014c244f60e72b8adb29b17905534801561003657600080fd5b50610182806100466000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80633a6feadb14610030575b600080fd5b61003861003a565b005b60008060009054906101000a90046001600160a01b03166001600160a01b031663ecacaf0b6040518163ffffffff1660e01b81526004016020604051808303816000875af1158015610090573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906100b49190610135565b905060015b8181116101315760005460405163140e25ad60e31b8152600481018390526001600160a01b039091169063a0712d6890602401600060405180830381600087803b15801561010657600080fd5b505af115801561011a573d6000803e3d6000fd5b5050505080806101299061014e565b9150506100b9565b5050565b60006020828403121561014757600080fd5b5051919050565b60006001820161016e57634e487b7160e01b600052601160045260246000fd5b506001019056fea164736f6c634300080f000a";
const isSuperArgs = (xs) => xs.length > 1;
class WebbMultimint__factory extends ethers_1.ContractFactory {
    constructor(...args) {
        if (isSuperArgs(args)) {
            super(...args);
        }
        else {
            super(_abi, _bytecode, args[0]);
        }
    }
    deploy(overrides) {
        return super.deploy(overrides || {});
    }
    getDeployTransaction(overrides) {
        return super.getDeployTransaction(overrides || {});
    }
    attach(address) {
        return super.attach(address);
    }
    connect(signer) {
        return super.connect(signer);
    }
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.WebbMultimint__factory = WebbMultimint__factory;
WebbMultimint__factory.bytecode = _bytecode;
WebbMultimint__factory.abi = _abi;
