/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc1155Sol from "./ERC1155.sol";
export type { erc1155Sol };
export type { Owned } from "./Owned";
export type { WebbNFT } from "./WebbNFT";
export * as factories from "./factories";
export type { ERC1155 } from "./ERC1155.sol/ERC1155";
export { ERC1155__factory } from "./factories/ERC1155.sol/ERC1155__factory";
export type { ERC1155TokenReceiver } from "./ERC1155.sol/ERC1155TokenReceiver";
export { ERC1155TokenReceiver__factory } from "./factories/ERC1155.sol/ERC1155TokenReceiver__factory";
export { Owned__factory } from "./factories/Owned__factory";
export { WebbNFT__factory } from "./factories/WebbNFT__factory";
